//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminProject.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminProject.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamer People Yöneticisi.
        /// </summary>
        public static string adminTypeAdmin {
            get {
                return ResourceManager.GetString("adminTypeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamer People Editörü.
        /// </summary>
        public static string adminTypeEditor {
            get {
                return ResourceManager.GetString("adminTypeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamer People Yazarı.
        /// </summary>
        public static string adminTypeWriter {
            get {
                return ResourceManager.GetString("adminTypeWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha önce bu anketi oyladiniz..
        /// </summary>
        public static string afterVoteSurvey {
            get {
                return ResourceManager.GetString("afterVoteSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlgili kategori bulunamadı..
        /// </summary>
        public static string categoryNotFound {
            get {
                return ResourceManager.GetString("categoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Çok Beğenilenler.
        /// </summary>
        public static string contentFilterTypeTopRated {
            get {
                return ResourceManager.GetString("contentFilterTypeTopRated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizin İçin Seçtiklerimiz.
        /// </summary>
        public static string contentFilterTypeWeChose {
            get {
                return ResourceManager.GetString("contentFilterTypeWeChose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik bulunamadı..
        /// </summary>
        public static string contentNotFound {
            get {
                return ResourceManager.GetString("contentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail adresi bulunamadı..
        /// </summary>
        public static string emailNotFound {
            get {
                return ResourceManager.GetString("emailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail zorunludur..
        /// </summary>
        public static string emailRequired {
            get {
                return ResourceManager.GetString("emailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail gönderilirken bir hata oluştu. Lütfen tekrar deneyiniz..
        /// </summary>
        public static string emailSendingError {
            get {
                return ResourceManager.GetString("emailSendingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz e-mail adresinize gönderilmiştir..
        /// </summary>
        public static string emailSendPassword {
            get {
                return ResourceManager.GetString("emailSendPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen önce bir öğe seçiniz..
        /// </summary>
        public static string likeNotFound {
            get {
                return ResourceManager.GetString("likeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email veya parola hatalı..
        /// </summary>
        public static string loginError {
            get {
                return ResourceManager.GetString("loginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim zorunludur..
        /// </summary>
        public static string nameRequired {
            get {
                return ResourceManager.GetString("nameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut şifre yanlış..
        /// </summary>
        public static string oldPasswordIncorrect {
            get {
                return ResourceManager.GetString("oldPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut şifreniz zorunludur..
        /// </summary>
        public static string oldPasswordRequired {
            get {
                return ResourceManager.GetString("oldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistem degisikligi nedeniyle sifreniz guncellenip, {0} adresinize gönderilmistir. Yeni sifreniz ile giris yapabilirsiniz..
        /// </summary>
        public static string oldUserNewPassword {
            get {
                return ResourceManager.GetString("oldUserNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola tekrarı zorunludur..
        /// </summary>
        public static string passwordAgainRequired {
            get {
                return ResourceManager.GetString("passwordAgainRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre en az 6 en fazla 50 karakter olabilir..
        /// </summary>
        public static string passwordCharacterLenght {
            get {
                return ResourceManager.GetString("passwordCharacterLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parolalar uyuşmuyor..
        /// </summary>
        public static string passwordNotMatch {
            get {
                return ResourceManager.GetString("passwordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola zorunludur..
        /// </summary>
        public static string passwordRequired {
            get {
                return ResourceManager.GetString("passwordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyisim zorunludur..
        /// </summary>
        public static string surnameRequired {
            get {
                return ResourceManager.GetString("surnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soru veya cevap eksik..
        /// </summary>
        public static string surveyOrAnswerRequired {
            get {
                return ResourceManager.GetString("surveyOrAnswerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Hakkında Haber Sonuçları.
        /// </summary>
        public static string tagSearchPageTitle {
            get {
                return ResourceManager.GetString("tagSearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tümü.
        /// </summary>
        public static string typeAll {
            get {
                return ResourceManager.GetString("typeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınız yasaklanmıştır. Yasaklanma sebebi: {0}.
        /// </summary>
        public static string userBannedMessage {
            get {
                return ResourceManager.GetString("userBannedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcınız başarıyla oluşturulmuştur. Lütfen e-mail adresinize gönderilen aktivasyon mailini güncelleyeniz..
        /// </summary>
        public static string userCreatedMessage {
            get {
                return ResourceManager.GetString("userCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcının hesabı pasif durumdadır..
        /// </summary>
        public static string userDeactive {
            get {
                return ResourceManager.GetString("userDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcının hesabı silinmiş..
        /// </summary>
        public static string userDeleted {
            get {
                return ResourceManager.GetString("userDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail daha önce kullanılmış..
        /// </summary>
        public static string userEmailUsed {
            get {
                return ResourceManager.GetString("userEmailUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen önce kullanıcı girişi yapınız..
        /// </summary>
        public static string userLoginCheck {
            get {
                return ResourceManager.GetString("userLoginCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail ve parola zorunludur..
        /// </summary>
        public static string usernameOrPasswordRequired {
            get {
                return ResourceManager.GetString("usernameOrPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınız henüz onaylanmamış. Lütfen aktivasyon mailinizi kontrol ediniz..
        /// </summary>
        public static string userUnapproved {
            get {
                return ResourceManager.GetString("userUnapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgileriniz başarıyla güncellendi..
        /// </summary>
        public static string userUpdateMessage {
            get {
                return ResourceManager.GetString("userUpdateMessage", resourceCulture);
            }
        }
    }
}
