// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Sihirdar.DataAccessLayer.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sliderTableAddTypeField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sliderTableAddTypeField));
        
        string IMigrationMetadata.Id
        {
            get { return "201702192345384_sliderTableAddTypeField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
