// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Sihirdar.DataAccessLayer.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SurveyTableChangeQuestionTypeField2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SurveyTableChangeQuestionTypeField2));
        
        string IMigrationMetadata.Id
        {
            get { return "201702070040475_SurveyTableChangeQuestionTypeField2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
