// <auto-generated />
namespace Sihirdar.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class skidAddColStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(skidAddColStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201709071605097_skidAddColStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
